"""Tests for TournamentDispatcher — pairing generation and queue integration."""

from __future__ import annotations

from pathlib import Path
from unittest.mock import MagicMock

import pytest

from keisei.config import MatchSchedulerConfig
from keisei.db import _connect, init_db
from keisei.training.match_scheduler import MatchScheduler
from keisei.training.opponent_store import EntryStatus, OpponentEntry, OpponentStore, Role
from keisei.training.tournament_dispatcher import TournamentDispatcher
from keisei.training.tournament_queue import (
    claim_next_pairing,
    get_active_queue_depth,
    get_round_status,
)


@pytest.fixture
def db(tmp_path: Path) -> str:
    path = str(tmp_path / "test.db")
    init_db(path)
    return path


@pytest.fixture
def store(db: str, tmp_path: Path) -> OpponentStore:
    league_dir = str(tmp_path / "league")
    Path(league_dir).mkdir(exist_ok=True)
    return OpponentStore(db_path=db, league_dir=league_dir)


def _seed_entries(store: OpponentStore, n: int = 5) -> list[OpponentEntry]:
    """Insert real entries via raw SQL and return them."""
    conn = _connect(store.db_path)
    try:
        for i in range(n):
            conn.execute(
                "INSERT INTO league_entries "
                "(display_name, architecture, model_params, "
                "checkpoint_path, elo_rating, created_epoch, "
                "games_played, created_at, flavour_facts, "
                "role, status, update_count) "
                "VALUES (?, 'resnet', '{}', ?, 1000.0, ?, 0, "
                "'2026-01-01', '[]', 'dynamic', 'active', 0)",
                (f"e{i}", f"/p/{i}.pt", i),
            )
        conn.commit()
    finally:
        conn.close()
    return store.list_entries()


class TestTournamentDispatcher:
    def test_enqueues_round_pairings(self, store: OpponentStore) -> None:
        _seed_entries(store, 5)
        sched = MatchScheduler(MatchSchedulerConfig())
        disp = TournamentDispatcher(
            store=store, scheduler=sched, games_per_match=3,
        )
        round_id = disp.enqueue_round(epoch=5)
        assert round_id is not None
        status = get_round_status(store.db_path, round_id)
        assert status["pending"] == 10

    def test_round_id_monotonic(self, store: OpponentStore) -> None:
        _seed_entries(store, 3)
        sched = MatchScheduler(MatchSchedulerConfig())
        disp = TournamentDispatcher(
            store=store, scheduler=sched, games_per_match=3,
        )
        r1 = disp.enqueue_round(epoch=1)
        r2 = disp.enqueue_round(epoch=2)
        assert r1 is not None and r2 is not None
        assert r2 > r1

    def test_skip_when_pool_too_small(self, store: OpponentStore) -> None:
        _seed_entries(store, 2)
        sched = MatchScheduler(MatchSchedulerConfig())
        disp = TournamentDispatcher(
            store=store, scheduler=sched, min_pool_size=3,
        )
        assert disp.enqueue_round(epoch=0) is None
        assert get_active_queue_depth(store.db_path) == 0

    def test_returns_none_for_empty_pool(self, store: OpponentStore) -> None:
        sched = MatchScheduler(MatchSchedulerConfig())
        disp = TournamentDispatcher(
            store=store, scheduler=sched, min_pool_size=0,
        )
        assert disp.enqueue_round(epoch=0) is None

    def test_check_round_completion(self, store: OpponentStore) -> None:
        _seed_entries(store, 3)
        sched = MatchScheduler(MatchSchedulerConfig())
        scorer = MagicMock()
        scorer.pair_priority = MagicMock(return_value=0.0)
        disp = TournamentDispatcher(
            store=store, scheduler=sched, priority_scorer=scorer,
        )
        round_id = disp.enqueue_round(epoch=0)
        assert round_id is not None
        assert disp.check_round_completion(round_id) is False

        while True:
            claim = claim_next_pairing(store.db_path, worker_id="w0")
            if claim is None:
                break
            from keisei.training.tournament_queue import mark_pairing_done
            mark_pairing_done(store.db_path, claim.id, status="done")

        assert disp.check_round_completion(round_id) is True
        scorer.advance_round.assert_called_once()

    def test_pairings_claimable_by_workers(self, store: OpponentStore) -> None:
        """Pairings generated by dispatcher are claimable by workers."""
        _seed_entries(store, 3)
        sched = MatchScheduler(MatchSchedulerConfig())
        disp = TournamentDispatcher(
            store=store, scheduler=sched, games_per_match=3,
        )
        disp.enqueue_round(epoch=0)
        claimed = claim_next_pairing(store.db_path, worker_id="w0")
        assert claimed is not None
        assert claimed.games_target == 3
