name: 'Setup Project Environment'
description: 'Sets up Python, caches dependencies, and installs project requirements'
runs:
  using: "composite"
  steps:
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      shell: bash

    - name: Cache uv dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Install dependencies
      run: |
        uv venv .venv
        source .venv/bin/activate
        uv pip install -e ".[dev]"
        echo "$PWD/.venv/bin" >> $GITHUB_PATH
      shell: bash
